### ISSUE TITLE
插件无法安装

### ISSUE THREAD

**Issue by sheldonxxd** [jiix/plugins#1]
把插件文件放到Plugin路径下，虽然能在后台显示插件，点击安装也提示安装成功，但是插件并没有应用？？

![图片](https://user-images.githubusercontent.com/42539486/91924407-2afc0400-ed05-11ea-8fa4-536a335807b5.png)

![图片](https://user-images.githubusercontent.com/42539486/91924421-364f2f80-ed05-11ea-8aa3-b4a4ec2f2856.png)

![图片](https://user-images.githubusercontent.com/42539486/91924442-4535e200-ed05-11ea-8ca7-7ce692d2c8c1.png)

可以看到发新贴的时候，感觉插件并没有应用成功阿

**Comment by jiix** [comment]
先后台清空缓存，再强制刷新页面

**Comment by sheldonxxd** [comment]
谢谢，发现是plugin的子目录权限并非全部可读写导致的。
